{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sahool-postgres
spec:
  type: ClusterIP
  selector:
    app: sahool-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sahool-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sahool-postgres
  template:
    metadata:
      labels:
        app: sahool-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
{{- end }}
