apiVersion: v1
kind: Secret
metadata:
  name: sahool-db-credentials
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.db | quote }}
