apiVersion: v1
kind: Secret
metadata:
  name: sahool-minio-credentials
type: Opaque
stringData:
  accessKey: {{ .Values.minio.rootUser | quote }}
  secretKey: {{ .Values.minio.rootPassword | quote }}
